version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: iben
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: mydatabase
      PGDATA: /data/postgres
    ports:
      - "5332:5432"
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
