version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata  # more conventional path
    ports:
      - "5332:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db-data:
